//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pabpro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zadaniepabAEntities : DbContext
    {
        public zadaniepabAEntities()
            : base("name=zadaniepabAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Drużyna> Drużyna { get; set; }
        public DbSet<Entity_9> Entity_9 { get; set; }
        public DbSet<Mecz> Mecz { get; set; }
        public DbSet<Miejsca> Miejsca { get; set; }
        public DbSet<Terminarz> Terminarz { get; set; }
        public DbSet<Trener> Trener { get; set; }
        public DbSet<Zawodnik> Zawodnik { get; set; }
        public DbSet<Zdarzenia> Zdarzenia { get; set; }
        public DbSet<Przynależność> Przynależność { get; set; }
    }
}
