//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pabpro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przynależność
    {
        public int Przy_ID { get; set; }
        public Nullable<int> Drużyna_ID { get; set; }
        public Nullable<int> Zawodnik_ID { get; set; }
        public System.DateTime Od_kiedy { get; set; }
        public System.DateTime Do_kiedy { get; set; }
        public string Pozycja { get; set; }
        public string Stawka { get; set; }
    
        public virtual Drużyna Drużyna { get; set; }
        public virtual Zawodnik Zawodnik { get; set; }
    }
}
