//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pabpro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminarz
    {
        public Terminarz()
        {
            this.Mecz = new HashSet<Mecz>();
        }
    
        public int Treminarz_ID { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual ICollection<Mecz> Mecz { get; set; }
    }
}
