//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pabpro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zawodnik
    {
        public Zawodnik()
        {
            this.Entity_9 = new HashSet<Entity_9>();
            this.Przynależność = new HashSet<Przynależność>();
        }
    
        public int Zawodnik_ID { get; set; }
        public string Zawodnik_Imię { get; set; }
        public string Zawodnik_Nazwisko { get; set; }
    
        public virtual ICollection<Entity_9> Entity_9 { get; set; }
        public virtual ICollection<Przynależność> Przynależność { get; set; }
    }
}
