//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pabpro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zdarzenia
    {
        public Zdarzenia()
        {
            this.Entity_9 = new HashSet<Entity_9>();
        }
    
        public int Zdarzenia_ID { get; set; }
        public Nullable<int> Mecz_ID { get; set; }
        public string Kary { get; set; }
        public string Wejścia_na_boisko { get; set; }
        public string Zejścia_z_boiska { get; set; }
        public string Rzut_rożny { get; set; }
        public string Strzelone_bramki { get; set; }
    
        public virtual ICollection<Entity_9> Entity_9 { get; set; }
        public virtual Mecz Mecz { get; set; }
    }
}
